version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"  # Web
      - "5672:5672"    # RabbitMQ port
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  productores:
    build:
      context: ./Productores
      dockerfile: Dockerfile
    # container_name: "productores"
    environment:
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672"
    depends_on:
      - rabbitmq
    restart: always

  trabajadores:
    build:
      context: ./Trabajadores
      dockerfile: Dockerfile
    #container_name: "trabajadores"
    environment:
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672"
    depends_on:
      - rabbitmq
    restart: always

  trabajadores-externos:
    build:
      context: ./Trabajadores-externos/T-externo-1
      dockerfile: Dockerfile
    #container_name: "trabajadores-externos"
    environment:
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672"
    depends_on:
      - rabbitmq
    restart: always

volumes:
  rabbitmq_data:
